import type { Metadata } from "next";
import {
  Inter_Tight,
  Geist,
  Geist_Mono,
  DM_Serif_Display,
} from "next/font/google";
import "./globals.css";
import { GameStateProvider } from "@/context/gameState";
import PageTransition from "@/components/transition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const Inter_Tight_ = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight: "400",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DMSerif_Display = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GameStateProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${Inter_Tight_.variable} ${geistMono.variable} ${DMSerif_Display.variable} h-full antialiased`}
      >
        <body
          className="min-h-full flex flex-col"
          style={{ viewTransitionName: "page-content" }}
        >
          {children}
        </body>
      </html>
    </GameStateProvider>
  );
}
