export const words = [
  {
    actual: "Oral Contraceptive",
    german: "Antibabypille",
    cards: ["Anti", "Baby", "Pill"],
    category: "Items",
  },
  {
    actual: "Turtle",
    german: "Schildkröte",
    cards: ["Shield", "Toad"],
    category: "Animals",
  },
  {
    actual: "Glove",
    german: "Handschuh",
    cards: ["Hand", "Shoe"],
    category: "Clothing",
  },
  {
    actual: "Seal",
    german: "Seehund",
    cards: ["Sea", "Dog"],
    category: "Animals",
  },
  {
    actual: "Slug",
    german: "Nacktschnecke",
    cards: ["Naked", "Snail"],
    category: "Animals",
  },
  {
    actual: "Raccoon",
    german: "Waschbär",
    cards: ["Wash", "Bear"],
    category: "Animals",
  },
  {
    actual: "Porcupine",
    german: "Stachelschwein",
    cards: ["Spike", "Pig"],
    category: "Animals",
  },
  {
    actual: "Bat",
    german: "Fledermaus",
    cards: ["Flutter", "Mouse"],
    category: "Animals",
  },
  {
    actual: "Skunk",
    german: "Stinktier",
    cards: ["Stink", "Animal"],
    category: "Animals",
  },
  {
    actual: "Sloth",
    german: "Faultier",
    cards: ["Lazy", "Animal"],
    category: "Animals",
  },
  {
    actual: "Lightbulb",
    german: "Glühbirne",
    cards: ["Glow", "Pear"],
    category: "Items",
  },
  {
    actual: "Vacuum",
    german: "Staubsauger",
    cards: ["Dust", "Sucker"],
    category: "Items",
  },
  {
    actual: "Hospital",
    german: "Krankenhaus",
    cards: ["Sick", "House"],
    category: "Places",
  },
  {
    actual: "Ambulance",
    german: "Krankenwagen",
    cards: ["Sick", "Wagon"],
    category: "Vehicles",
  },
  {
    actual: "Squid",
    german: "Tintenfisch",
    cards: ["Ink", "Fish"],
    category: "Animals",
  },
  {
    actual: "Nipple",
    german: "Brustwarze",
    cards: ["Breast", "Wart"],
    category: "Anatomy",
  },
  {
    actual: "Gums",
    german: "Zahnfleisch",
    cards: ["Tooth", "Meat"],
    category: "Anatomy",
  },
  {
    actual: "Diarrhea",
    german: "Durchfall",
    cards: ["Through", "Fall"],
    category: "Anatomy",
  },
  {
    actual: "Rib Cage",
    german: "Brustkorb",
    cards: ["Breast", "Basket"],
    category: "Anatomy",
  },
  {
    actual: "Middle Finger",
    german: "Stinkefinger",
    cards: ["Stink", "Finger"],
    category: "Anatomy",
  },
  {
    actual: "Rhino",
    german: "Nashorn",
    cards: ["Nose", "Horn"],
    category: "Animals",
  },
  {
    actual: "Platypus",
    german: "Schnabeltier",
    cards: ["Beak", "Animal"],
    category: "Animals",
  },
  {
    actual: "Armadillo",
    german: "Gürteltier",
    cards: ["Belt", "Animal"],
    category: "Animals",
  },
  {
    actual: "Hippo",
    german: "Nilpferd",
    cards: ["Nile", "Horse"],
    category: "Animals",
  },
  {
    actual: "Polar Bear",
    german: "Eisbär",
    cards: ["Ice", "Bear"],
    category: "Animals",
  },
  {
    actual: "Tarantula",
    german: "Vogelspinne",
    cards: ["Bird", "Spider"],
    category: "Animals",
  },
  {
    actual: "Lighter",
    german: "Feuerzeug",
    cards: ["Fire", "Thing"],
    category: "Items",
  },
  {
    actual: "Airplane",
    german: "Flugzeug",
    cards: ["Flight", "Thing"],
    category: "Vehicles",
  },
  {
    actual: "Toy",
    german: "Spielzeug",
    cards: ["Play", "Thing"],
    category: "Items",
  },
  {
    actual: "Tool",
    german: "Werkzeug",
    cards: ["Work", "Thing"],
    category: "Items",
  },
  {
    actual: "Drum Set",
    german: "Schlagzeug",
    cards: ["Beat", "Thing"],
    category: "Items",
  },
  {
    actual: "Fridge",
    german: "Kühlschrank",
    cards: ["Cool", "Cabinet"],
    category: "Items",
  },
  {
    actual: "Flashlight",
    german: "Taschenlampe",
    cards: ["Pocket", "Lamp"],
    category: "Items",
  },
  {
    actual: "Tissue",
    german: "Taschentuch",
    cards: ["Pocket", "Cloth"],
    category: "Items",
  },
  {
    actual: "Towel",
    german: "Handtuch",
    cards: ["Hand", "Cloth"],
    category: "Items",
  },
  {
    actual: "Nurse",
    german: "Krankenschwester",
    cards: ["Sick", "Sister"],
    category: "People",
  },
  {
    actual: "Dentist",
    german: "Zahnarzt",
    cards: ["Tooth", "Doctor"],
    category: "People",
  },
  {
    actual: "Veterinarian",
    german: "Tierarzt",
    cards: ["Animal", "Doctor"],
    category: "People",
  },
  {
    actual: "Employee",
    german: "Arbeitnehmer",
    cards: ["Work", "Taker"],
    category: "People",
  },
  {
    actual: "Employer",
    german: "Arbeitgeber",
    cards: ["Work", "Giver"],
    category: "People",
  },
  {
    actual: "Thimble",
    german: "Fingerhut",
    cards: ["Finger", "Hat"],
    category: "Items",
  },
  {
    actual: "Umbrella",
    german: "Regenschirm",
    cards: ["Rain", "Screen"],
    category: "Items",
  },
  {
    actual: "Ice Skate",
    german: "Schlittschuh",
    cards: ["Sled", "Shoe"],
    category: "Items",
  },
  {
    actual: "Stroller",
    german: "Kinderwagen",
    cards: ["Child", "Wagon"],
    category: "Items",
  },
  {
    actual: "Fried Egg",
    german: "Spiegelei",
    cards: ["Mirror", "Egg"],
    category: "Food",
  },
  {
    actual: "Cotton",
    german: "Baumwolle",
    cards: ["Tree", "Wool"],
    category: "Materials",
  },
  {
    actual: "Queue",
    german: "Warteschlange",
    cards: ["Wait", "Snake"],
    category: "Concepts",
  },
  {
    actual: "Skyscraper",
    german: "Wolkenkratzer",
    cards: ["Cloud", "Scraper"],
    category: "Places",
  },
  {
    actual: "Airport",
    german: "Flughafen",
    cards: ["Flight", "Port"],
    category: "Places",
  },
  {
    actual: "Train Station",
    german: "Bahnhof",
    cards: ["Train", "Yard"],
    category: "Places",
  },
  {
    actual: "Dictionary",
    german: "Wörterbuch",
    cards: ["Word", "Book"],
    category: "Items",
  },
  {
    actual: "Diary",
    german: "Tagebuch",
    cards: ["Day", "Book"],
    category: "Items",
  },
  {
    actual: "Television",
    german: "Fernsehen",
    cards: ["Far", "Seeing"],
    category: "Items",
  },
  {
    actual: "Headphones",
    german: "Kopfhörer",
    cards: ["Head", "Hearer"],
    category: "Items",
  },
  {
    actual: "Sewing Machine",
    german: "Nähmaschine",
    cards: ["Sew", "Machine"],
    category: "Items",
  },
  {
    actual: "Trash Can",
    german: "Mülleimer",
    cards: ["Garbage", "Bucket"],
    category: "Items",
  },
  {
    actual: "Desk",
    german: "Schreibtisch",
    cards: ["Write", "Table"],
    category: "Items",
  },
  {
    actual: "Peninsula",
    german: "Halbinsel",
    cards: ["Half", "Island"],
    category: "Geography",
  },
  {
    actual: "Birthmark",
    german: "Muttermal",
    cards: ["Mother", "Mark"],
    category: "Anatomy",
  },
];
